version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: normalniy
      POSTGRES_DB: payment
      PGDATA: /var/lib/postgres/data/
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d todolist_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge