server:
  host: "localhost"
  port: 8080

database:
  host: "localhost" # заменить на "db" для запуска внутри Docker-контейнера
  port: 5432
  dbname: "payment"
  sslmode: "disable"
  max_idle_conns: 15
  max_open_conns: 100
  conn_max_lifetime: 5